name: Discord-MCPE
author: Niekert
version: "1.0.2"
api:
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
softdepend: PurePerms
main: Niekert\DiscordMCPE\Main
commands:
    discord:
        description: Send an message to Discord!
        permission: discord.send
        usage: /discord MESSAGE
        aliases: [dc]
permissions:
    discord.send:
        default: op
