name: Discord-MCPE
author: Niekert
version: "1.0.0"
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
main: Niekert\DiscordMCPE\Main

commands:
    discord:
        description: Send an message to Discord!
        permission: discord.send
        usage: /discord MESSAGE
        aliases: [dc]

permissions:
    discord.send:
        default: op
